version: '3.8'
services:
  postgres:
    image: postgres:13.3
    restart: always
    ports:
      - 2345:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
